In [2]:
import numpy as np
a = np.array([1,2,3])

In [21]:
b = np.array([[4,5,6], [7,8,9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [29]:
## Get Dimension
a.ndim
b.ndim

2

In [30]:
#get shape [position]
a.shape
b.shape

(2, 3)

In [31]:
#Get Type
a.dtype

dtype('int64')

In [32]:
#Get size
a.itemsize

8

In [34]:
#get a specific row
b[0,:]

array([4, 5, 6])

In [35]:
#get a specific column
b[:,0]

array([4, 7])

In [39]:
c = np.random?

In [ ]:
c = np.random

In [ ]:
c = np.random.arange

In [3]:
c = np.random.rand(100)

In [5]:
d = np.arange(100)

In [6]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [53]:
np.full((2,2), 55)

array([[55, 55],
       [55, 55]])

In [54]:
##any other number(Full like)
np.full_like(a,4)

array([4, 4, 4])

In [10]:
### Random decimal numbers
np.random.rand(4,2)*100

array([[39.63430091, 56.05215777],
       [94.08467138, 25.27221663],
       [72.89714733, 36.40170068],
       [89.95902264, 81.10807683]])

In [58]:
np.random.random_sample(a.shape)

array([0.02644344, 0.30956042, 0.48994687])

In [64]:
#random integer values
np.random.randint(7, size=(3,3))

array([[3, 1, 6],
       [4, 2, 4],
       [1, 4, 0]])

In [67]:
#identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [70]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
z= np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [78]:
output[1:4,1:4]= z
output


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
## Be carefull when copying arrays

a = np.array([1,2,3])
b = a.copy()

In [80]:
b[0] = 10

In [11]:
a

array([1, 2, 3])

In [12]:
##mathematics
a + 2



array([3, 4, 5])

In [13]:
a * 2

array([2, 4, 6])

In [14]:
a / 2

array([0.5, 1. , 1.5])

In [19]:
a * 2

array([14, 16, 18])

In [25]:
a += 2
a

array([19, 20, 21])

In [30]:
b = np.array([1,0,1])

In [31]:
a + b

array([20, 20, 22])

In [32]:
np.sin(a)

array([0.14987721, 0.91294525, 0.83665564])

In [33]:
np.cos(b)

array([0.54030231, 1.        , 0.54030231])

In [36]:
###### Linear Algebra

In [37]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [38]:
np.matmul(a,b)  # matrix multiplication

array([[6., 6.],
       [6., 6.]])

In [40]:
c = np.identity(3)
np.linalg.det(c)   ##determinants

1.0

In [42]:
### Statistics

stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats, axis = 1) ### min of 1st and 2nd row

array([1, 4])

In [48]:
np.max(stats, axis=0) ## all the values in the row

array([4, 5, 6])

In [50]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [52]:
### reorganizing arrays

before = np.array([[1,2,3,4], [5,6,7,8]])
print(before.shape)

(2, 4)


In [53]:
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [55]:
after = before.reshape(4,2)
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
### vertically stacking vectors

In [58]:
v1 = np.array([1,2,3,4])
v2 = np.array([6,7,8,9])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [1, 2, 3, 4],
       [6, 7, 8, 9]])

In [59]:
## Horizontal stack

In [60]:
v1 = np.array([1,2,3,4])
v2 = np.array([6,7,8,9])

In [61]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 6, 7, 8, 9])

In [62]:
### loading databases

In [70]:
filedata = np.genfromtxt("data.txt", delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [71]:
### Boolean Masking and Advanced Indexing

In [72]:
filedata[filedata > 50]

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [73]:
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [75]:
np.any(filedata > 50, axis=0)   ## axis 0 means looking at data column wise

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [76]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [77]:
a = np.arange(1,31)

In [78]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [79]:
a.shape

(30,)

In [84]:
after = a.reshape(6,5)
after

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [88]:
after[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [92]:
after[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [100]:
after [[0, 0, 4,4,5,5], [3,4, 3, 4, 3, 4]]

array([ 4,  5, 24, 25, 29, 30])

In [102]:
after [[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])